COMP_PATH=$$PWD

INCLUDEPATH += $$COMP_PATH

SOURCES += \
    $$COMP_PATH/qtmaterialavatar.cpp \
    $$COMP_PATH/lib/qtmaterialstyle.cpp \
    $$COMP_PATH/lib/qtmaterialtheme.cpp \
    $$COMP_PATH/qtmaterialbadge.cpp \
    $$COMP_PATH/lib/qtmaterialoverlaywidget.cpp \
    $$COMP_PATH/qtmaterialcheckbox.cpp \
    $$COMP_PATH/lib/qtmaterialcheckable_internal.cpp \
    $$COMP_PATH/lib/qtmaterialcheckable.cpp \
    $$COMP_PATH/lib/qtmaterialripple.cpp \
    $$COMP_PATH/lib/qtmaterialrippleoverlay.cpp \
    $$COMP_PATH/qtmaterialfab.cpp \
    $$COMP_PATH/qtmaterialraisedbutton.cpp \
    $$COMP_PATH/qtmaterialflatbutton_internal.cpp \
    $$COMP_PATH/qtmaterialflatbutton.cpp \
    $$COMP_PATH/lib/qtmaterialstatetransition.cpp \
    $$COMP_PATH/qtmaterialiconbutton.cpp \
    $$COMP_PATH/qtmaterialprogress_internal.cpp \
    $$COMP_PATH/qtmaterialprogress.cpp \
    $$COMP_PATH/qtmaterialcircularprogress_internal.cpp \
    $$COMP_PATH/qtmaterialcircularprogress.cpp \
    $$COMP_PATH/qtmaterialslider_internal.cpp \
    $$COMP_PATH/qtmaterialslider.cpp \
    $$COMP_PATH/qtmaterialsnackbar_internal.cpp \
    $$COMP_PATH/qtmaterialsnackbar.cpp \
    $$COMP_PATH/qtmaterialradiobutton.cpp \
    $$COMP_PATH/qtmaterialtoggle_internal.cpp \
    $$COMP_PATH/qtmaterialtoggle.cpp \
    $$COMP_PATH/qtmaterialtextfield_internal.cpp \
    $$COMP_PATH/qtmaterialtextfield.cpp \
    $$COMP_PATH/qtmaterialtabs_internal.cpp \
    $$COMP_PATH/qtmaterialtabs.cpp \
    $$COMP_PATH/qtmaterialscrollbar_internal.cpp \
    $$COMP_PATH/qtmaterialscrollbar.cpp \
    $$COMP_PATH/qtmaterialdialog_internal.cpp \
    $$COMP_PATH/qtmaterialdialog.cpp \
    $$COMP_PATH/qtmaterialdrawer_internal.cpp \
    $$COMP_PATH/qtmaterialdrawer.cpp \
    $$COMP_PATH/qtmaterialappbar.cpp \
    $$COMP_PATH/qtmaterialautocomplete.cpp \
    $$COMP_PATH/qtmaterialpaper.cpp \
    $$COMP_PATH/qtmaterialtable.cpp \
    $$COMP_PATH/layouts/qtmaterialsnackbarlayout.cpp \
    $$COMP_PATH/qtmaterialautocomplete_internal.cpp \
    $$COMP_PATH/qtmaterialmenu.cpp \
    $$COMP_PATH/qtmaterialmenu_internal.cpp \
    $$COMP_PATH/qtmateriallist.cpp \
    $$COMP_PATH/qtmateriallistitem.cpp
HEADERS += \
    $$COMP_PATH/qtmaterialavatar_p.h \
    $$COMP_PATH/qtmaterialavatar.h \
    $$COMP_PATH/lib/qtmaterialstyle_p.h \
    $$COMP_PATH/lib/qtmaterialstyle.h \
    $$COMP_PATH/lib/qtmaterialtheme_p.h \
    $$COMP_PATH/lib/qtmaterialtheme.h \
    $$COMP_PATH/qtmaterialbadge_p.h \
    $$COMP_PATH/qtmaterialbadge.h \
    $$COMP_PATH/lib/qtmaterialoverlaywidget.h \
    $$COMP_PATH/qtmaterialcheckbox_p.h \
    $$COMP_PATH/qtmaterialcheckbox.h \
    $$COMP_PATH/lib/qtmaterialcheckable_internal.h \
    $$COMP_PATH/lib/qtmaterialcheckable_p.h \
    $$COMP_PATH/lib/qtmaterialripple.h \
    $$COMP_PATH/lib/qtmaterialrippleoverlay.h \
    $$COMP_PATH/lib/qtmaterialcheckable.h \
    $$COMP_PATH/qtmaterialfab_p.h \
    $$COMP_PATH/qtmaterialfab.h \
    $$COMP_PATH/qtmaterialraisedbutton_p.h \
    $$COMP_PATH/qtmaterialraisedbutton.h \
    $$COMP_PATH/qtmaterialflatbutton_internal.h \
    $$COMP_PATH/qtmaterialflatbutton_p.h \
    $$COMP_PATH/qtmaterialflatbutton.h \
    $$COMP_PATH/lib/qtmaterialstatetransition.h \
    $$COMP_PATH/lib/qtmaterialstatetransitionevent.h \
    $$COMP_PATH/qtmaterialiconbutton_p.h \
    $$COMP_PATH/qtmaterialiconbutton.h \
    $$COMP_PATH/qtmaterialprogress_internal.h \
    $$COMP_PATH/qtmaterialprogress_p.h \
    $$COMP_PATH/qtmaterialprogress.h \
    $$COMP_PATH/qtmaterialcircularprogress_internal.h \
    $$COMP_PATH/qtmaterialcircularprogress_p.h \
    $$COMP_PATH/qtmaterialcircularprogress.h \
    $$COMP_PATH/qtmaterialslider_internal.h \
    $$COMP_PATH/qtmaterialslider_p.h \
    $$COMP_PATH/qtmaterialslider.h \
    $$COMP_PATH/qtmaterialsnackbar_internal.h \
    $$COMP_PATH/qtmaterialsnackbar_p.h \
    $$COMP_PATH/qtmaterialsnackbar.h \
    $$COMP_PATH/qtmaterialradiobutton_p.h \
    $$COMP_PATH/qtmaterialradiobutton.h \
    $$COMP_PATH/qtmaterialtoggle_internal.h \
    $$COMP_PATH/qtmaterialtoggle_p.h \
    $$COMP_PATH/qtmaterialtoggle.h \
    $$COMP_PATH/qtmaterialtextfield_internal.h \
    $$COMP_PATH/qtmaterialtextfield_p.h \
    $$COMP_PATH/qtmaterialtextfield.h \
    $$COMP_PATH/qtmaterialtabs_internal.h \
    $$COMP_PATH/qtmaterialtabs_p.h \
    $$COMP_PATH/qtmaterialtabs.h \
    $$COMP_PATH/qtmaterialscrollbar_internal.h \
    $$COMP_PATH/qtmaterialscrollbar_p.h \
    $$COMP_PATH/qtmaterialscrollbar.h \
    $$COMP_PATH/qtmaterialdialog_internal.h \
    $$COMP_PATH/qtmaterialdialog_p.h \
    $$COMP_PATH/qtmaterialdialog.h \
    $$COMP_PATH/qtmaterialdrawer_internal.h \
    $$COMP_PATH/qtmaterialdrawer_p.h \
    $$COMP_PATH/qtmaterialdrawer.h \
    $$COMP_PATH/qtmaterialappbar.h \
    $$COMP_PATH/qtmaterialappbar_p.h \
    $$COMP_PATH/qtmaterialautocomplete.h \
    $$COMP_PATH/qtmaterialautocomplete_p.h \
    $$COMP_PATH/qtmaterialpaper.h \
    $$COMP_PATH/qtmaterialpaper_p.h \
    $$COMP_PATH/qtmaterialtable.h \
    $$COMP_PATH/qtmaterialtable_p.h \
    $$COMP_PATH/layouts/qtmaterialsnackbarlayout.h \
    $$COMP_PATH/layouts/qtmaterialsnackbarlayout_p.h \
    $$COMP_PATH/qtmaterialautocomplete_internal.h \
    $$COMP_PATH/qtmaterialmenu.h \
    $$COMP_PATH/qtmaterialmenu_p.h \
    $$COMP_PATH/qtmaterialmenu_internal.h \
    $$COMP_PATH/qtmateriallist.h \
    $$COMP_PATH/qtmateriallist_p.h \
    $$COMP_PATH/qtmateriallistitem.h \
    $$COMP_PATH/qtmateriallistitem_p.h \
    $$PWD/lib/qtmaterialconst.h

RESOURCES += \
    $$COMP_PATH/material_res.qrc
